name: Multi-Job Workflow B

on:
  workflow_run:
    workflows: [Multi-Job Workflow]
    types:
      - completed

jobs:
  job1:
    name: Pull Source Code
    runs-on: [self-hosted, Linux, X64, aws]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files
        run: pwd && ls -l

  job2:
    needs: job1
    name: Terraform Plan
    runs-on: [self-hosted, Linux, X64, aws]
    
    steps:
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        run: date && terraform plan -out=tfplan.binary && terraform show -json tfplan.binary > tfplan.json

  job3:
    needs: job2
    name: Run IP Address Command
    runs-on: [self-hosted, Linux, X64, aws]
    steps:
      - name: Display IP Address
        run: ip a && whoami

  job6:
    needs: job2
    name: Run IP Address Command branch
    runs-on: [self-hosted, Linux, X64, aws]
    steps:
      - name: Display IP Address
        run: ip a && whoami

  job4:
    needs: job3
    name: Run Snyk Scan IAC
    continue-on-error: true
    runs-on: [self-hosted, Linux, X64, aws]
    steps:
      - name: IAC Scan No Custom Policy
        working-directory: ./terraform
        run: snyk iac test --rules=/home/ubuntu/customrules/custom.tar.gz  --report --sarif-file-output=./test_saja --org=pruclement --policy-path=/home/ubuntu/.snyk

  job5:
    needs: job4
    if: success() 
    name: No Vuln
    runs-on: [self-hosted, Linux, X64, aws]
    steps:
      - name: Display Hostname
        run: hostname

  job7:
    needs: job4
    if: failure() 
    name: Vuln detected
    runs-on: [self-hosted, Linux, X64, aws]
    steps:
      - name: Display Hostname
        run: hostname

